// AUTH
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CHECK_TOKEN = "AUTH_CHECK_TOKEN";

// USER

export const SET_USER = "SET_USER";
export const EDIT_USER = "EDIT_USER";

// PROJECTS

export const SET_PROJECTS = "SET_PROJECTS";
export const PROJECT_CREATE = "PROJECT_CREATE";
export const PROJECT_DELETE = "PROJECT_DELETE";
export const PROJECT_UPDATE = "PROJECT_UPDATE";

// CATEGORIES

export const SET_CATEGORIES = "SET_CATEGORIES";
export const CATEGORY_CREATE = "CATEGORY_CREATE";
export const CATEGORY_DELETE = "CATEGORY_DELETE";
export const CATEGORY_UPDATE = "CATEGORY_UPDATE";

// CARDS

export const CARD_CREATE = "CARD_CREATE";
export const CARD_DELETE = "CARD_DELETE";
export const CARD_UPDATE = "CARD_UPDATE";
